import { useState } from "react"
import { characters } from "../../data/characters"
import { getCast } from "../../features/cast/castData"
import type { DialogueLogEntry, GameState } from "../../engine/types"

type Props = { state: Pick<GameState, "scenarioId" | "flags">; log: DialogueLogEntry[]; currentCharacterIds: string[]; onClose: () => void }
const mutualLabels = new Set(["婚約", "夫婦", "親子", "共同作戦"])
export function CastModal({ state, log, currentCharacterIds, onClose }: Props) {
  const [tab, setTab] = useState<"relation" | "characters">("relation")
  const cast = getCast(state, log, currentCharacterIds)
  const [selectedId, setSelectedId] = useState(cast.characters[0]?.id ?? "")
  const selected = cast.characters.find((character) => character.id === selectedId) ?? cast.characters[0]
  const related = cast.relations.filter((relation) => relation.from === selected?.id || relation.to === selected?.id)
  const portrait = (id: string, large = false) => <div className={`cast-portrait ${large ? "cast-portrait--center" : ""}`}>{characters[id].expressions.neutral?.imagePath ? <img src={characters[id].expressions.neutral.imagePath} alt="" /> : null}</div>
  return <section className="cast-modal" role="dialog" aria-modal="true" aria-labelledby="cast-title"><div className="cast-modal__panel"><header><div><p>CAST</p><h2 id="cast-title">人物と関係を振り返る</h2></div><button type="button" onClick={onClose}>閉じる</button></header><div className="cast-modal__tabs" role="tablist"><button type="button" role="tab" aria-selected={tab === "relation"} onClick={() => setTab("relation")}>RELATION</button><button type="button" role="tab" aria-selected={tab === "characters"} onClick={() => setTab("characters")}>CHARACTERS</button></div>{tab === "relation" ? <div className="cast-modal__content"><div className="cast-person-picker">{cast.characters.map((character) => <button type="button" key={character.id} className={character.id === selected?.id ? "is-selected" : ""} aria-pressed={character.id === selected?.id} onClick={() => setSelectedId(character.id)}>{character.name}</button>)}</div>{selected && <section className="cast-relation-focus"><div className="cast-center-card">{portrait(selected.id, true)}<h3>{selected.name}</h3><p>{selected.description}</p>{selected.status && <span className="cast-status">{selected.status}</span>}</div><div className="cast-relation-grid">{related.length ? related.map((relation) => { const other = relation.from === selected.id ? relation.to : relation.from; const directional = !mutualLabels.has(relation.label); const direction = !directional ? "↔" : relation.from === selected.id ? "→" : "←"; return <article className="cast-relation-card" key={`${relation.from}-${relation.to}-${relation.label}`}>{portrait(other)}<div><h4>{characters[other].name}</h4><p className="cast-relation-card__label">{direction} <strong>{relation.label}</strong></p><p className="cast-relation-card__hint">{directional ? relation.from === selected.id ? `${selected.name}から${characters[other].name}へ` : `${characters[other].name}から${selected.name}へ` : `${selected.name}と${characters[other].name}`}</p></div></article> }) : <p>現在、直接判明している関係はありません。</p>}</div></section>}<p className="cast-modal__note">中心人物と、現在までに判明した直接の関係だけを表示しています。</p></div> : <div className="cast-modal__content cast-character-list">{cast.characters.map((character) => { const imagePath = characters[character.id].expressions.neutral?.imagePath; return <article key={character.id}><div className="cast-character-list__portrait">{imagePath ? <img src={imagePath} alt="" /> : null}</div><div><h3>{character.name}</h3><p>{character.description}</p>{character.status && <b>{character.status}</b>}{character.relations.map((relation) => <span key={relation}>{relation}</span>)}</div></article> })}</div>}</div></section>
}
